### ISSUE TITLE
Can I ask you a question about React Native Map?

### ISSUE THREAD

**Issue by qiuqiyuan** [tugorez/react-native#1]
Hi tugorez,

You mentioned here at [airbnb-map](https://github.com/airbnb/react-native-maps/issues/100) that you are able to load markers in based on user region.

I am not sure how I can do it without re-rendering the entire <MapView>, could you please give me some hint on how you achieved it?

**Comment by tugorez** [comment]
Hi @qiuqiyuan sorry for being late. 
Yes for sure, I'm using [redux](https://github.com/reactjs/redux), [reselect](https://github.com/reactjs/reselect) and [redux-saga](https://github.com/redux-saga/redux-saga) are you familiarized with those awesome libraries?

**Comment by tugorez** [comment]
Or if you have any code to show I think I could help you :)

**Comment by qiuqiyuan** [comment]
Hi @tugorez, I got it working by using js promise and setting react native component state not props.

Thank you so much for getting back to me :D.
